[project]
name = "clipdozer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.6"
dependencies = [
    "moviepy>=2.2.1",
    "imageio-ffmpeg>=0.5.1",
    "PySide6>=6.10.0",
    "pillow>=11.2.0",
    "numpy>=1.26.0",
]
